name: 'build' 
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

env:
  ARTIFACT_DIR: .nerves/outup

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v2

      - uses: actions/cache@v3
        with:
          path: |
            deps
            _build
            .nerves
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.2
        with:
          runCmd: mix deps.get && mix nerves.artifact --path $ARTIFACT_DIR
      
      - name: List artifacts
        run: |
          ls -lah $ARTIFACT_DIR

      - uses: actions/upload-artifact@v3
        with:
          name: nerves_system_rpi3a_64bit
          path: .nerves/dl/nerves_system_rpi3a_64bit-portable*.tar.gz
          if-no-files-found: error