name: 'build' 
on:
  pull_request:
  push:
    branches:
      - main
  tags:
    - 'v*'

env:
  ARTIFACT_DIR: .nerves/output

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v2

      - uses: actions/cache@v3
        with:
          path: |
            deps
            _build
            .nerves
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Build the Docker image
        run: |
          docker build .devcontainer/ --build-arg UID=$(id -u) --build-arg GID=$(id -g) -t nerves_rpi3_64bit 

      - name: Build artifact
        run: |
          mkdir -p $ARTIFACT_DIR
          docker run -v $(pwd):/app --workdir /app -t nerves_rpi3_64bit bash -c "mix deps.get && mix nerves.artifact --path /app/$ARTIFACT_DIR"
      
      - name: List artifacts
        run: |
          find . -name nerves_system_rpi3a_64bit*.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: nerves_system_rpi3a_64bit
          path: $ARTIFACT_DIR/nerves_system_rpi3a_64bit-portable-*.tar.gz
          if-no-files-found: warn

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: $ARTIFACT_DIR/*

      - name: Clean-up
        run: |
          rm $ARTIFACT_DIR/*