name: 'build' 
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - 'v*'

env:
  ARTIFACT_DIR: .nerves/output

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Get git state
        run: echo "GIT_DESC=$(git describe --tags)" >> $env:GITHUB_ENV

      - uses: actions/cache@v3
        with:
          path: |
            deps
            _build
            .nerves
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Build the Docker image
        run: |
          docker build .devcontainer/ --build-arg UID=$(id -u) --build-arg GID=$(id -g) -t nerves_rpi3_64bit 

      - name: Build artifact
        run: |
          mkdir -p ${{ env.ARTIFACT_DIR }}
          docker run -v $(pwd):/app --workdir /app -t nerves_rpi3_64bit bash -c "mix deps.get && mix nerves.artifact --path /app/${{ env.ARTIFACT_DIR }}"
      
      - name: List artifacts
        run: |
          find . -name nerves_system_rpi3a_64bit*.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: nerves_system_rpi3a_64bit-${{ env.GIT_DESC }}.tar.gz
          path: ${{ env.ARTIFACT_DIR }}/nerves_system_rpi3a_64bit-portable-*.tar.gz
          if-no-files-found: error

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.ARTIFACT_DIR }}/*

      - name: Clean-up
        run: |
          rm ${{ env.ARTIFACT_DIR }}/*